name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - beta
      - candidate/stable
      - testdocs

jobs:
  deploy:
    permissions:
      contents: write      # This allows writing to the repository contents
      pages: write         # This allows deploying to GitHub Pages
      id-token: write      # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          cd docs/
          conda install -c conda-forge --file requirements.txt

      - name: Build Beta Docs
        run: |
          git checkout beta
          cd docs/
          mkdocs build
          mkdir -p ../gh-pages/beta
          cp -R site/* ../gh-pages/beta

      - name: Build Stable Docs
        run: |
          git checkout candidate/stable
          cd docs/
          mkdocs build
          mkdir -p ../gh-pages/stable
          cp -R site/* ../gh-pages/stable

      - name: Create Redirect Index
        run: |
          echo '<!DOCTYPE html>
          <html>
            <head>
              <meta http-equiv="refresh" content="0; url=beta/" />
            </head>
            <body>
              <p>Redirecting to the latest beta documentation...</p>
            </body>
          </html>' > ./gh-pages/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
